### ISSUE TITLE
Stuck on syncFilter with latest update

### ISSUE THREAD

**Issue by hshar7** [ConsenSys/eventeum#148]
Tried to used latest master and tried with latest development but both are not starting the service.. It's stuck on:

```
2020-09-01 00:28:50.021 [main] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Start block number for node default: 7117593
2020-09-01 00:28:50.021 [main] INFO  net.consensys.eventeum.service.sync.DefaultEventSyncService: syncFilter - Syncing event filter with id myEvent from block 7083273 to 7117593
```

Any ideas?

**Comment by hshar7** [comment]
I had to for some reason include a default for the contract and startFrom parameters in the applications yml:
`contractAddress: ${CONTRACT_ADDRESS:0x0}` and `startBlock: ${START_BLOCK:9482978}`

**Comment by craigwilliams84** [comment]
Hi @hshar, could you post the configuration that caused Eventeum to become stuck?  I'd like to look into it some more.

**Comment by ahmetson** [comment]
I am facing the same issue. My application.yml that I attach to the docker-compose.

```eventFilters:
  - id: MoonbaseAlphaLighthouseTierWrapperClaim
    contractAddress: ${MOVR_TIER_WRAPPER_ADDRESS:0x0}
    eventSpecification:
      eventName: Claim
      indexedParameterDefinitions:
        - position: 0
          type: ADDRESS
        - position: 1
          type: UINT8
      # nonIndexedParameterDefinitions:
        # - position: 2
          # type: BYTES32
    correlationId:
      type: INDEXED_PARAMETER
      index: 0
    startBlock: ${MOVR_TIER_WRAPPER_START_BLOCK:1166625}
  - id: MoonbaseAlphaLighthouseTierWrapperUse
    contractAddress: 0xeFfdB75Ff90349151E100D82Dfd38fa1d7f050D2
    eventSpecification:
      eventName: Use
      indexedParameterDefinitions:
        - position: 0
          type: ADDRESS
        - position: 1
          type: UINT8
    correlationId:
      type: INDEXED_PARAMETER
      index: 0
    startBlock: 1166625
```

Docker-compose part that runs the Eventeum: 

```
  eventeum:        
    image: eventeum/eventeum:latest
    container_name: "eventeum"
    ports:
    - "8060:8060"
    depends_on:
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_BLOCKSTRATEGY: PUBSUB
      ETHEREUM_NODE_URL: wss://moonbeam-alpha.api.onfinality.io/rpc?apikey=2982c921-32d9-49a3-adf6-5783be2f526f
      # ETHEREUM_NODE_URL: wss://rinkeby.infura.io/ws/v3/12b4124bfb784eb8bd2c788f2981782d
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:19092
    volumes:
      - type: bind
        source: ./application.yml
        target: /application.yml
    env_file:
      - ./.env
    networks:
      - net
 ```

and the .env that contains the address of the file: 

```
MOVR_TIER_WRAPPER_ADDRESS=0xeFfdB75Ff90349151E100D82Dfd38fa1d7f050D2
MOVR_TIER_WRAPPER_START_BLOCK=1166625
```

However, eventeum is stuck at syncing, and in the loop logs the following two lines:

```
2021-12-02 14:31:55.821 [main] INFO  net.consensys.eventeum.chain.service.block.DefaultBlockNumberService: getStartBlockForNode - Start block number for node default: 1278578
2021-12-02 14:31:55.822 [main] INFO  net.consensys.eventeum.service.sync.DefaultEventSyncService: syncFilter - Syncing event filter with id MoonbaseAlphaLighthouseTierWrapperClaim from block 1166625 to 1278578
```

I am using the Moonriver network. Connected to the Moonriver network through Websockets provided by https://onfinality.io/.
Atleast it returns the block number.
